version: "3"

services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./:/go/src/app
    restart: always
    depends_on:
      - db
  db:
    image: mysql:8.0.19
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/conf.d:/etc/mysql/conf.d
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
